### ISSUE TITLE
Adding more tools

### ISSUE THREAD

**Issue by Yehonal** [wowgaming/client-dev-kit#1]
Hi @Helias 

I'm pretty sure you've more tools to edit dbc stuff

can you create a revision here and upload them please?

**Comment by Helias** [comment]
I do not recommend **MyDBCEditor**, it is a bit buggy, for months I didn't understand what I did wrong during the edit of a DBC file, when I changed the editor I realize that MyDBCEditor made something wrong during the edit.

I strongly recommend **WDBX** https://github.com/WowDevTools/WDBXEditor
it converts DBC to CSV, SQL and reverse, moreover, it supports from 0.x Alpha to last DBC version.

I would suggest to change the repo name into client-dev-kit and maybe add more tools related to the more formats MPQ, BLP,  ADT etc.

**Comment by Yehonal** [comment]
yep definetly! I'm going to update it
